<div class="span3">&nbsp;</div>
<div class="span6">
      <div class="widget">
        <div class="widget-header">
          <h3>Proveedores</h3>
        </div>
        <!-- /widget-header -->
        <div class="widget-content">
          <div class="shortcuts"> 
              <a href="proveedores/crear" class="shortcut"><i class="shortcut-icon icon-user"></i><span class="shortcut-label">Registro de Proveedores</span> </a>
              <a href="clientes/identificacion/<?php echo $usuario ?>" class="shortcut"><i class="shortcut-icon icon-list-alt"></i><span class="shortcut-label">Tipo de Identificación</span> </a>
              <a href="proveedores/tipos" class="shortcut"><i class="shortcut-icon icon-male"></i> <span class="shortcut-label">Tipos de Proveedores</span> </a>
              <a href="proveedores/cond_pago" class="shortcut"> <i class="shortcut-icon icon-dollar"></i><span class="shortcut-label">Condición de Pago</span> </a>
          </div>
          <!-- /shortcuts --> 
        </div>
        <!-- /widget-content --> 
</div>
<div class="span3">&nbsp;</div>